spring:
  application:
    name: bookt
  datasource:
    url: jdbc:postgresql://localhost:5432/bookt?options=-c%20timezone=UTC
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info